name: GitHub Pages Deployment

concurrency:
    group: production
    cancel-in-progress: true

on:
    push:
        branches: [develop]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20.10.0"
            - name: Build and deploy website
              run: npm run deploy
